version: '3'
services:
  redis:
    restart: always
    image: redis:5.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data
  app:
    restart: always
    build: .
    environment:
      - LANG=en_US.UTF-8 
      - RUBYOPT=-EUTF-8
      - REDIS_HOST=redis
    links:
      - redis
